### PR TITLE
[Maintenance] Migrate travis to github actions

### PR DESCRIPTION
**Pull request by lchrusciel**
The current testing pipeline is not working. Either it should be migrated to travis.com or Github actions (or any other CI :)). As we are using GH actions in Sylius and quite happy about it, hence is my proposal.

The build will be almost for sure red now, but to work on it, I would need someone to turn on github action for this repo.

Also, I would recommend start dropping old, unmaintained versions of PHP and Symfony.

/cc @winzou

### CODE REVIEW

**Comment by winzou** [comment]
Hi @lchrusciel, thanks for your PR!
I'm OK with Github actions. I haven't use it before and I'm not sure how to turn it on. Would you mind if I add you as collaborator on the repos? So that you can manage it directly and avoid back and forth with my unexisting skills on this topic :)
Also, even if I do take care of this package, I think it's a good thing for you guys that someone at Sylius is also able to maintain it, we never know what happens.

**Comment by lchrusciel** [comment]
Hey Alexandre! 

Sure, it would make some stuff easier :) I will probably push forward a few topics here, so probably will ask for your approval now and then.

**Comment by winzou** [comment]
Sure!
I've just invited you as a collaborator on both state machine repos.

**Comment by lchrusciel** [comment]
Hey Alexandre! 

Unfortunately, I don't have enough permissions to do something about GitHub CI yet. Can you check this card: 
image

And see if there is "enable" button. Also, can you check this configuration of the repository:
image

**Comment by winzou** [comment]
"Allow all actions" is already checked in the config. In the Actions tab it seems that there is no existing workflow. It looks like we just need to merge this PR to create a new workflow that we will appear in the Action tab. Is the PR ok to merge as is before you go on with a separate one?

**Comment by lchrusciel** [comment]
I assume, we may try this way 👍

**Pull request merged**
