### PR TITLE
Add Symfony 6 support

### PR DESCRIPTION
**Pull request by Zales0123**
Hello @winzou! 👋 Let's make this awesome library support Symfony 6 :)

### CODE REVIEW

**Comment by winzou** [comment]
Hi @Zales0123 
Thanks for your PR! How does it work with https://github.com/winzou/StateMachineBundle/pull/63?

**Comment by Zales0123** [comment]
🤷‍♂️ 😄 as far I see, the only thing deprecate with `Symfony\Component\DependencyInjection\ContainerInterface` is the usage of it in autowiring, the interface itself exist in Symfony 4, 5 and 6. Both of these PRs could probably be merged, they do not interfere with each other :)

**Comment by winzou** [comment]
Thanks!

**Comment by winzou** [comment]
Tagged 0.6.0

**Pull request merged**
